.PHONY: run build test lint tidy proto docker-up docker-down

run:
	go run ./cmd/{{.service_name}}

build:
	CGO_ENABLED=0 go build -o bin/server ./cmd/{{.service_name}}

test:
	go test -race -cover ./...

lint:
	golangci-lint run ./...

tidy:
	go mod tidy

{{- if or (eq .transport "grpc") (eq .transport "both")}}

proto:
	buf generate
{{- end}}
{{- if .include_docker}}

docker-up:
	docker compose up --build -d

docker-down:
	docker compose down
{{- end}}
